version: '3'

services:
  postgres:
    image: postgres:15
    container_name: 'java-postgres'
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: TyBaranina01
        POSTGRES_DB: shopBD
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
        - postgres
    container_name: 'java-back'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopBD
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: TyBaranina01


